services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=rodeio_admin
      - POSTGRES_PASSWORD=rodeio_secure_pass_2026
      - POSTGRES_DB=rodeio_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://rodeio_admin:rodeio_secure_pass_2026@db:5432/rodeio_db?schema=public
      - PRISMA_CLIENT_ENGINE_TYPE=library
      - NEXTAUTH_URL_INTERNAL=http://localhost:3000
    depends_on:
      - db
    restart: always
