version: "3.8"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: rodeio_admin
      POSTGRES_PASSWORD: rodeio_secure_pass_2026
      POSTGRES_DB: rodeio_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - rede

  app:
    image: ghcr.io/cristhian-sancore/rodeio-pro:latest
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: postgresql://rodeio_admin:rodeio_secure_pass_2026@db:5432/rodeio_db?schema=public
      NEXTAUTH_URL: https://rodeio.cristhiansancore.com.br
      NEXTAUTH_SECRET: rodeio-super-secret-key-2026
      AUTH_TRUST_HOST: "true"
      PRISMA_CLIENT_ENGINE_TYPE: library
      NEXTAUTH_URL_INTERNAL: http://localhost:3000
    volumes:
      - ./rodeio_uploads:/app/public/uploads
      - ./rodeio_prisma:/app/prisma
    depends_on:
      - db
    restart: always
    networks:
      - rede

networks:
  rede:
    external: true
